# Generated by Django 4.1.3 on 2022-12-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_userinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Videos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("url", models.TextField()),
                ("imageUrl", models.TextField()),
                ("description", models.TextField()),
                ("isActive", models.BooleanField()),
            ],
        ),
    ]
