# Generated by Django 4.1.3 on 2022-12-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_blogentry_slug_alter_foodblog_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogentry",
            name="image",
            field=models.ImageField(upload_to="blogs"),
        ),
        migrations.AlterField(
            model_name="foodblog",
            name="image",
            field=models.ImageField(upload_to="blogs"),
        ),
    ]
